print('Hello Human, what is your name ?')
name = input()
print("Hello", name)
print('So,',name, 'how old are you ?')
age = input()
age = int(age)
bin_age = bin(age)
print('So, next year you will be', age + 1)
print('You should know that your age in binary is ', bin_age)